### ISSUE TITLE
Registering output is picking free port incorrectly

### ISSUE THREAD

**Issue by wkozyra95** [membraneframework/membrane_video_compositor_plugin#157]
https://github.com/membraneframework/membrane_video_compositor_plugin/blob/master/lib/membrane/video_compositor/streams_handler.ex

Not sure why this even works, but the output port can't be picked based on the response from the compositor. Only the listening side knows if the port is free or not.

Also slightly related, this logic is consuming all their response errors and returns just `:error` atom. If there is a code where we try range of values and all of them fail we should at least return last of first error.

**Comment by WojciechBarczynski** [comment]
Yep, It was initially done this way since VC didn't have the option to specify port range. It should be fixed.

This works fine as long as the port isn't taken in the meantime (between checking in the plugin and registering on the VC side), but should be done on VC side

**Comment by wkozyra95** [comment]
> Yep, It was initially done this way since VC didn't have the option to specify port range. It should be fixed.

I'm talking about output stream not inputs. There is no (and it can't ever be) option to specifiy that range in compositor

> This works fine as long as the port isn't taken in the meantime (between checking in the plugin and registering on the VC side), but should be done on VC side

I don't think this is true. Unless I missed sth there is no checking at all whether port is free. Request to register output will always succeed regardless whether port if free or not

**Comment by WojciechBarczynski** [comment]
Oh, sorry, I got it wrong.

To handle it correctly, we should:
- Try to spawn the UPD source for output and recover by trying the other port in the case of an error (port taken / not available). This could be "optimized" by firstly checking if the port is free (but it can be taken after check - TOCTOU problem).
-  After successful spawn of UDP source register output with the request.

Also, for inputs:
- Instead of trying to use individual ports specify a range in the register input request.
